# Font
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0

# General
foreground       #cdd6f4
background       #1e1e2e
background_opacity    1
selection_foreground #1e1e2e
selection_background #f9e2af
cursor           #f9e2af
cursor_shape block
cursor_shape_unfocused block
cursor_blink_interval 0
shell_integration no-cursor
active_border_color #f9e2af
inactive_border_color #313244
tab_bar_style    powerline
modify_font cell_height 120%
macos_show_window_title_in none
macos_titlebar_color #1e1e2e
macos_menubar_title_max_length 0
mouse_hide_wait -1

color0  #242424
color1  #ff6e6e
color2  #a3f7b5
color3  #fff3a3
color4  #82aaff
color5  #c792ea
color6  #89ddff
color7  #d0d0d0
color8  #4e4e4e
color9  #ff8b8b
color10 #b9fbc0
color11 #ffe9a9
color12 #9cc4ff
color13 #e1b7ff
color14 #aaf0ff
color15 #f5f5f5

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5 
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 10
